// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EstateProManager.Models;

public partial class EstateProManagerContext : DbContext
{
    public EstateProManagerContext(DbContextOptions<EstateProManagerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Contrat> Contrats { get; set; }

    public virtual DbSet<Demande> Demandes { get; set; }

    public virtual DbSet<Propriete> Proprietes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Tach> Taches { get; set; }

    public virtual DbSet<Utilisateur> Utilisateurs { get; set; }

    public virtual DbSet<Vente> Ventes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contrat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contrats__3214EC07447F1DB6");

            entity.Property(e => e.PaiementMensuel).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdLocataireNavigation).WithMany(p => p.Contrats)
                .HasForeignKey(d => d.IdLocataire)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contrats__IdLoca__2C3393D0");

            entity.HasOne(d => d.IdProprieteNavigation).WithMany(p => p.Contrats)
                .HasForeignKey(d => d.IdPropriete)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contrats__IdProp__2B3F6F97");
        });

        modelBuilder.Entity<Demande>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Demandes__3214EC07D33E4B29");

            entity.Property(e => e.DetailsDemande).IsRequired();
            entity.Property(e => e.TypeDemande).IsRequired();

            entity.HasOne(d => d.IdProprieteNavigation).WithMany(p => p.Demandes)
                .HasForeignKey(d => d.IdPropriete)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Demandes__IdProp__33D4B598");

            entity.HasOne(d => d.IdUtilisateurNavigation).WithMany(p => p.Demandes)
                .HasForeignKey(d => d.IdUtilisateur)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Demandes__IdUtil__34C8D9D1");
        });

        modelBuilder.Entity<Propriete>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Propriet__3214EC0736E8C92B");

            entity.Property(e => e.Caracteristiques).IsRequired();
            entity.Property(e => e.Documents).IsRequired();
            entity.Property(e => e.Emplacement).IsRequired();
            entity.Property(e => e.Images).IsRequired();
            entity.Property(e => e.Type).IsRequired();
            entity.Property(e => e.Valeur).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07A44F3C13");

            entity.Property(e => e.Libelle).HasColumnName("libelle");
        });

        modelBuilder.Entity<Tach>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Taches__3214EC076FB6A2E7");

            entity.Property(e => e.DetailsTache).IsRequired();
            entity.Property(e => e.StatutTache).IsRequired();

            entity.HasOne(d => d.IdDemandeNavigation).WithMany(p => p.Taches)
                .HasForeignKey(d => d.IdDemande)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Taches__IdDemand__37A5467C");

            entity.HasOne(d => d.IdPrestataireNavigation).WithMany(p => p.Taches)
                .HasForeignKey(d => d.IdPrestataire)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Taches__IdPresta__38996AB5");
        });

        modelBuilder.Entity<Utilisateur>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Utilisat__3214EC07949A8F51");

            entity.Property(e => e.Birthdate).HasColumnName("birthdate");
            entity.Property(e => e.Cin).HasColumnName("CIN");
            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.MotDePasse).IsRequired();
            entity.Property(e => e.Nom).IsRequired();
            entity.Property(e => e.Prenom).IsRequired();

            entity.HasOne(d => d.IdRoleNavigation).WithMany(p => p.Utilisateurs)
                .HasForeignKey(d => d.IdRole)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Utilisate__IdRol__267ABA7A");
        });

        modelBuilder.Entity<Vente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ventes__3214EC077DD9863D");

            entity.Property(e => e.PrixVente).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IdAcheteurNavigation).WithMany(p => p.VenteIdAcheteurNavigations)
                .HasForeignKey(d => d.IdAcheteur)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventes__IdAchete__300424B4");

            entity.HasOne(d => d.IdProprieteNavigation).WithMany(p => p.Ventes)
                .HasForeignKey(d => d.IdPropriete)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventes__IdPropri__2F10007B");

            entity.HasOne(d => d.IdVendeurNavigation).WithMany(p => p.VenteIdVendeurNavigations)
                .HasForeignKey(d => d.IdVendeur)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ventes__IdVendeu__30F848ED");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}