// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstateProManager.Models;

public partial class Contrat
{
    public long Id { get; set; }

    public long IdPropriete { get; set; }

    public long IdLocataire { get; set; }

    public DateOnly DateDebut { get; set; }

    public DateOnly DateFin { get; set; }

    public decimal PaiementMensuel { get; set; }

    public virtual Utilisateur IdLocataireNavigation { get; set; }

    public virtual Propriete IdProprieteNavigation { get; set; }
}