// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstateProManager.Models;

public partial class Demande
{
    public long Id { get; set; }

    public long IdPropriete { get; set; }

    public long IdUtilisateur { get; set; }

    public string TypeDemande { get; set; }

    public string DetailsDemande { get; set; }

    public virtual Propriete IdProprieteNavigation { get; set; }

    public virtual Utilisateur IdUtilisateurNavigation { get; set; }

    public virtual ICollection<Tach> Taches { get; set; } = new List<Tach>();
}