// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstateProManager.Models;

public partial class Propriete
{
    public long Id { get; set; }

    public string Type { get; set; }

    public long Taille { get; set; }

    public string Emplacement { get; set; }

    public string Caracteristiques { get; set; }

    public string Images { get; set; }

    public string Documents { get; set; }

    public decimal? Valeur { get; set; }

    public DateOnly? DateDeConstruction { get; set; }

    public virtual ICollection<Contrat> Contrats { get; set; } = new List<Contrat>();

    public virtual ICollection<Demande> Demandes { get; set; } = new List<Demande>();

    public virtual ICollection<Vente> Ventes { get; set; } = new List<Vente>();
}