// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstateProManager.Models;

public partial class Utilisateur
{
    public long Id { get; set; }

    public string Cin { get; set; }

    public string Nom { get; set; }

    public string Prenom { get; set; }

    public string Email { get; set; }

    public string MotDePasse { get; set; }

    public DateOnly Birthdate { get; set; }

    public string NumeroDeTelephone { get; set; }

    public string AdressePostale { get; set; }

    public long IdRole { get; set; }

    public virtual ICollection<Contrat> Contrats { get; set; } = new List<Contrat>();

    public virtual ICollection<Demande> Demandes { get; set; } = new List<Demande>();

    public virtual Role IdRoleNavigation { get; set; }

    public virtual ICollection<Tach> Taches { get; set; } = new List<Tach>();

    public virtual ICollection<Vente> VenteIdAcheteurNavigations { get; set; } = new List<Vente>();

    public virtual ICollection<Vente> VenteIdVendeurNavigations { get; set; } = new List<Vente>();
}