// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EstateProManager.Models;

public partial class Vente
{
    public long Id { get; set; }

    public long IdPropriete { get; set; }

    public long IdAcheteur { get; set; }

    public long IdVendeur { get; set; }

    public decimal PrixVente { get; set; }

    public DateOnly DateVente { get; set; }

    public virtual Utilisateur IdAcheteurNavigation { get; set; }

    public virtual Propriete IdProprieteNavigation { get; set; }

    public virtual Utilisateur IdVendeurNavigation { get; set; }
}